name: trackizer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2
#------------------ PACKAGE ------------------#
dependencies:
  flutter:
    sdk: flutter

  # ICONS
  cupertino_icons: ^1.0.8

  # STATE MANAGEMENT
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  
  # UI
  intl: ^0.18.0
  calendar_agenda:
    path: dev_lib/calendar_agenda

  # DataBase
  isar: ^3.1.0+1

  # UTILIS
  path_provider: ^2.1.5
  dio: ^5.9.0
  go_router: ^16.2.1
  scrollable_positioned_list: ^0.3.8
  flutter_speed_dial: ^7.0.0
  flutter_credit_card: ^4.1.0
  stacked_card_carousel: ^0.0.4
#------------------./ PACKAGE END ------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
#------------------- FONTES & ASSETS -------------------#
# ASSETS
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/fonts/
    - assets/icons/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/const/
  filename: assets.dart

  # FONTS
fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
      - asset: assets/fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
